{
    'name': 'Smart Manufacturing',
    'version': '1.0',
    'summary': 'Custom manufacturing features for Odoo 19',
    'category': 'Manufacturing',
    'author': 'ProcessDrive',
    'depends': ['mrp', 'purchase', 'stock', 'hr', 'maintenance', 'mail'],
    'data': [
        'security/manufacturing_groups.xml',
        'security/ir.model.access.csv',
        'wizard/mrp_create_bom_wizard_views.xml',
        'wizard/mrp_shop_floor_wizard_views.xml',
        'wizard/mrp_subcontracting_receive_wizard_views.xml',
        'wizard/mrp_subcontracting_delivery_wizard_views.xml',
        'views/mrp_workcenter_views.xml',
        'views/mrp_shop_floor_views.xml',
        'views/mrp_quality_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_subcontracting_views.xml',
        'views/mrp_dashboard_reports.xml',
        'views/res_config_settings_views.xml',
        'views/product_template_views.xml',
        'views/hr_employee_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'manufacturing/static/src/xml/shop_floor_kanban.xml',
            'manufacturing/static/src/js/shop_floor_kanban.js',
            'manufacturing/static/src/css/shop_floor_standalone.css',
        ],
        'web.assets_frontend': [
            'manufacturing/static/src/xml/scoped_app_templates.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
